ALTER TABLE leads
    ADD COLUMN IF NOT EXISTS ai_status VARCHAR(32);

ALTER TABLE leads
    ADD COLUMN IF NOT EXISTS ai_score INTEGER;

ALTER TABLE leads
    ADD COLUMN IF NOT EXISTS ai_summary TEXT;

ALTER TABLE leads
    ADD COLUMN IF NOT EXISTS ai_error TEXT;
