// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/dashboard" | "/dashboard/ai-assistant" | "/dashboard/calendar" | "/dashboard/goals" | "/dashboard/history" | "/dashboard/manager/create-agent" | "/dashboard/manager/forecast" | "/dashboard/manager/history" | "/dashboard/manager/lead-form" | "/dashboard/manager/leads" | "/dashboard/manager/overview" | "/dashboard/manager/reports" | "/dashboard/notifications" | "/dashboard/profile" | "/dashboard/report" | "/dashboard/settings" | "/dashboard/tasks" | "/forgot-password" | "/invite/accept" | "/lead-form" | "/login" | "/manager/leads/[leadId]" | "/report" | "/reset-password" | "/signup/choose-plan" | "/signup/company" | "/signup/create-account" | "/signup/google-onboarding-company" | "/status"
type PageRoutes = never
type LayoutRoutes = "/" | "/dashboard"
type RedirectRoutes = never
type RewriteRoutes = "/api-proxy/[[...path]]"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/api-proxy/[[...path]]": { "path"?: string[]; }
  "/dashboard": {}
  "/dashboard/ai-assistant": {}
  "/dashboard/calendar": {}
  "/dashboard/goals": {}
  "/dashboard/history": {}
  "/dashboard/manager/create-agent": {}
  "/dashboard/manager/forecast": {}
  "/dashboard/manager/history": {}
  "/dashboard/manager/lead-form": {}
  "/dashboard/manager/leads": {}
  "/dashboard/manager/overview": {}
  "/dashboard/manager/reports": {}
  "/dashboard/notifications": {}
  "/dashboard/profile": {}
  "/dashboard/report": {}
  "/dashboard/settings": {}
  "/dashboard/tasks": {}
  "/forgot-password": {}
  "/invite/accept": {}
  "/lead-form": {}
  "/login": {}
  "/manager/leads/[leadId]": { "leadId": string; }
  "/report": {}
  "/reset-password": {}
  "/signup/choose-plan": {}
  "/signup/company": {}
  "/signup/create-account": {}
  "/signup/google-onboarding-company": {}
  "/status": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/dashboard": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
