// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../src/app/dashboard/ai-assistant/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/ai-assistant">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/ai-assistant/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/calendar">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/goals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/goals">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/goals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/history">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/manager/create-agent/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/manager/create-agent">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/manager/create-agent/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/manager/forecast/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/manager/forecast">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/manager/forecast/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/manager/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/manager/history">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/manager/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/manager/lead-form/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/manager/lead-form">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/manager/lead-form/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/manager/leads/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/manager/leads">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/manager/leads/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/manager/overview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/manager/overview">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/manager/overview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/manager/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/manager/reports">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/manager/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/profile">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/report/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/report">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/report/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/tasks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/tasks">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/tasks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../src/app/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/invite/accept/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invite/accept">> = Specific
  const handler = {} as typeof import("../../src/app/invite/accept/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/lead-form/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lead-form">> = Specific
  const handler = {} as typeof import("../../src/app/lead-form/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/manager/leads/[leadId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/manager/leads/[leadId]">> = Specific
  const handler = {} as typeof import("../../src/app/manager/leads/[leadId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/report/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/report">> = Specific
  const handler = {} as typeof import("../../src/app/report/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset-password">> = Specific
  const handler = {} as typeof import("../../src/app/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/signup/choose-plan/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup/choose-plan">> = Specific
  const handler = {} as typeof import("../../src/app/signup/choose-plan/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/signup/company/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup/company">> = Specific
  const handler = {} as typeof import("../../src/app/signup/company/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/signup/create-account/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup/create-account">> = Specific
  const handler = {} as typeof import("../../src/app/signup/create-account/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/signup/google-onboarding-company/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup/google-onboarding-company">> = Specific
  const handler = {} as typeof import("../../src/app/signup/google-onboarding-company/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/status/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/status">> = Specific
  const handler = {} as typeof import("../../src/app/status/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../src/app/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
