import { CheckCircle2, Edit, XCircle } from 'lucide-react';

export const agents = [
  { id: 'alex-d', name: 'Alex Doe' },
  { id: 'john-p', name: 'John Popescu' },
  { id: 'maria-i', name: 'Maria Ionescu' },
];

export const teamPerformanceData = {
  calls: {
    '7': [
      { day: 'Luni', 'Alex Doe': 32, 'John Popescu': 25, 'Maria Ionescu': 40 },
      { day: 'Tue', 'Alex Doe': 45, 'John Popescu': 38, 'Maria Ionescu': 50 },
      {
        day: 'Miercuri',
        'Alex Doe': 28,
        'John Popescu': 33,
        'Maria Ionescu': 35,
      },
      { day: 'Joi', 'Alex Doe': 52, 'John Popescu': 48, 'Maria Ionescu': 55 },
      {
        day: 'Vineri',
        'Alex Doe': 61,
        'John Popescu': 55,
        'Maria Ionescu': 65,
      },
    ],
    '30': [
      {
        day: 'Wk 1',
        'Alex Doe': 218,
        'John Popescu': 190,
        'Maria Ionescu': 240,
      },
      {
        day: 'Wk 2',
        'Alex Doe': 250,
        'John Popescu': 220,
        'Maria Ionescu': 260,
      },
      {
        day: 'Wk 3',
        'Alex Doe': 230,
        'John Popescu': 210,
        'Maria Ionescu': 250,
      },
      {
        day: 'Wk 4',
        'Alex Doe': 280,
        'John Popescu': 260,
        'Maria Ionescu': 300,
      },
    ],
  },
  sales: {
    '7': [
      { day: 'Luni', 'Alex Doe': 2, 'John Popescu': 1, 'Maria Ionescu': 3 },
      { day: 'Tue', 'Alex Doe': 3, 'John Popescu': 2, 'Maria Ionescu': 4 },
      {
        day: 'Miercuri',
        'Alex Doe': 1,
        'John Popescu': 2,
        'Maria Ionescu': 2,
      },
      { day: 'Joi', 'Alex Doe': 4, 'John Popescu': 3, 'Maria Ionescu': 5 },
      { day: 'Vineri', 'Alex Doe': 5, 'John Popescu': 4, 'Maria Ionescu': 6 },
    ],
    '30': [
      {
        day: 'Wk 1',
        'Alex Doe': 15,
        'John Popescu': 12,
        'Maria Ionescu': 18,
      },
      {
        day: 'Wk 2',
        'Alex Doe': 18,
        'John Popescu': 15,
        'Maria Ionescu': 20,
      },
      {
        day: 'Wk 3',
        'Alex Doe': 16,
        'John Popescu': 14,
        'Maria Ionescu': 19,
      },
      {
        day: 'Wk 4',
        'Alex Doe': 22,
        'John Popescu': 19,
        'Maria Ionescu': 25,
      },
    ],
  },
};

export const agentReports = {
  'alex-d': {
    status: 'submitted',
    data: {
      outbound_dials: 61,
      pickups: 40,
      conversations_30s_plus: 35,
      sales_call_booked_from_outbound: 8,
      sales_call_on_calendar: 7,
      no_show: 1,
      reschedule_request: 0,
      cancel: 0,
      deposits: 5,
      sales_one_call_close: 3,
      followup_sales: 2,
      upsell_conversation_taken: 4,
      upsells: 1,
      contract_value: 12500,
      new_cash_collected: 5000,
      observations:
        'A productive day, most clients were receptive.',
      confirmation: true,
    },
  },
  'john-p': {
    status: 'draft',
    data: {
      outbound_dials: 55,
      pickups: 35,
      conversations_30s_plus: 30,
      sales_call_booked_from_outbound: 6,
      sales_call_on_calendar: 6,
      no_show: 0,
      reschedule_request: 1,
      cancel: 0,
      deposits: 4,
      sales_one_call_close: 2,
      followup_sales: 2,
      upsell_conversation_taken: 3,
      upsells: 1,
      contract_value: 9800,
      new_cash_collected: 4200,
      observations: 'We had a few reschedules. Follow-up needed tomorrow.',
      confirmation: false,
    },
  },
  'maria-i': {
    status: 'unfilled',
    data: {
      outbound_dials: 0,
      pickups: 0,
      conversations_30s_plus: 0,
      sales_call_booked_from_outbound: 0,
      sales_call_on_calendar: 0,
      no_show: 0,
      reschedule_request: 0,
      cancel: 0,
      deposits: 0,
      sales_one_call_close: 0,
      followup_sales: 0,
      upsell_conversation_taken: 0,
      upsells: 0,
      contract_value: 0,
      new_cash_collected: 0,
      observations: '',
      confirmation: false,
    },
  },
};

export const managerNotifications = [
  {
    id: 1,
    agent: 'Alex Doe',
    agentAvatarId: 'avatar-2',
    text: 'submitted the daily report.',
    time: '5 minute',
    read: false,
  },
  {
    id: 2,
    agent: 'John Popescu',
    agentAvatarId: 'avatar-1',
    text: 'saved a draft for the daily report.',
    time: '30 minute',
    read: false,
  },
  {
    id: 3,
    agent: 'Alex Doe',
    agentAvatarId: 'avatar-2',
    text: 'closed a sale of 2,500 RON.',
    time: '2 ore',
    read: true,
  },
  {
    id: 4,
    agent: 'Maria Ionescu',
    agentAvatarId: 'avatar-3',
    text: "requested edits to yesterday's report.",
    time: 'Yesterday',
    read: true,
  },
];

export const reportStatusConfig = {
  submitted: { text: 'Submitted', Icon: CheckCircle2, color: 'text-green-500' },
  draft: { text: 'Draft', Icon: Edit, color: 'text-yellow-500' },
  unfilled: { text: 'Necompletat', Icon: XCircle, color: 'text-destructive' },
  locked: { text: 'Locked', Icon: XCircle, color: 'text-muted-foreground' },
};

export const quickStats = {
  all: {
    calls: 116,
    conversions: 14,
    sales: 7,
    value: '$22,300',
  },
  'alex-d': {
    calls: 61,
    conversions: 8,
    sales: 5,
    value: '$12,500',
  },
  'john-p': {
    calls: 55,
    conversions: 6,
    sales: 4,
    value: '$9,800',
  },
  'maria-i': {
    calls: 0,
    conversions: 0,
    sales: 0,
    value: '$0',
  },
};

export const personalHistory = {
  last7Days: [
    {
      period: '6 days ago',
      sales: 2,
      calls: 30,
      followUpSales: 1,
      outboundBookings: 5,
    },
    {
      period: '5 days ago',
      sales: 3,
      calls: 45,
      followUpSales: 1,
      outboundBookings: 7,
    },
    {
      period: '4 days ago',
      sales: 1,
      calls: 28,
      followUpSales: 0,
      outboundBookings: 4,
    },
    {
      period: '3 days ago',
      sales: 4,
      calls: 52,
      followUpSales: 2,
      outboundBookings: 8,
    },
    {
      period: '2 days ago',
      sales: 3,
      calls: 48,
      followUpSales: 1,
      outboundBookings: 6,
    },
    {
      period: 'Yesterday',
      sales: 5,
      calls: 61,
      followUpSales: 3,
      outboundBookings: 10,
    },
    {
      period: 'Today',
      sales: 2,
      calls: 35,
      followUpSales: 1,
      outboundBookings: 4,
    },
  ],
  currentMonth: [
    {
      period: 'Wk 1',
      sales: 15,
      value: 37500,
      calls: 218,
      followUpSales: 5,
      outboundBookings: 30,
    },
    {
      period: 'Wk 2',
      sales: 18,
      value: 45000,
      calls: 250,
      followUpSales: 7,
      outboundBookings: 35,
    },
    {
      period: 'Wk 3',
      sales: 12,
      value: 30000,
      calls: 230,
      followUpSales: 4,
      outboundBookings: 28,
    },
    {
      period: 'Wk 4',
      sales: 20,
      value: 50000,
      calls: 280,
      followUpSales: 9,
      outboundBookings: 40,
    },
  ],
  currentYear: [
    {
      period: 'Ian',
      sales: 60,
      value: 150000,
      calls: 900,
      followUpSales: 20,
      outboundBookings: 120,
    },
    {
      period: 'Feb',
      sales: 55,
      value: 137500,
      calls: 850,
      followUpSales: 18,
      outboundBookings: 110,
    },
    {
      period: 'Mar',
      sales: 70,
      value: 175000,
      calls: 1000,
      followUpSales: 25,
      outboundBookings: 150,
    },
    {
      period: 'Apr',
      sales: 65,
      value: 162500,
      calls: 950,
      followUpSales: 22,
      outboundBookings: 140,
    },
    {
      period: 'Mai',
      sales: 75,
      value: 187500,
      calls: 1100,
      followUpSales: 30,
      outboundBookings: 160,
    },
    {
      period: 'Iun',
      sales: 80,
      value: 200000,
      calls: 1200,
      followUpSales: 35,
      outboundBookings: 180,
    },
    {
      period: 'Iul',
      sales: 82,
      value: 205000,
      calls: 1250,
      followUpSales: 38,
      outboundBookings: 190,
    },
    {
      period: 'Aug',
      sales: 0,
      value: 0,
      calls: 0,
      followUpSales: 0,
      outboundBookings: 0,
    },
    {
      period: 'Sep',
      sales: 0,
      value: 0,
      calls: 0,
      followUpSales: 0,
      outboundBookings: 0,
    },
    {
      period: 'Oct',
      sales: 0,
      value: 0,
      calls: 0,
      followUpSales: 0,
      outboundBookings: 0,
    },
    {
      period: 'Nov',
      sales: 0,
      value: 0,
      calls: 0,
      followUpSales: 0,
      outboundBookings: 0,
    },
    {
      period: 'Dec',
      sales: 0,
      value: 0,
      calls: 0,
      followUpSales: 0,
      outboundBookings: 0,
    },
  ],
  previousYear: [
    {
      period: 'Ian',
      sales: 50,
      value: 125000,
      calls: 800,
      followUpSales: 15,
      outboundBookings: 100,
    },
    {
      period: 'Feb',
      sales: 48,
      value: 120000,
      calls: 780,
      followUpSales: 14,
      outboundBookings: 95,
    },
    {
      period: 'Mar',
      sales: 65,
      value: 162500,
      calls: 950,
      followUpSales: 20,
      outboundBookings: 130,
    },
    {
      period: 'Apr',
      sales: 62,
      value: 155000,
      calls: 920,
      followUpSales: 19,
      outboundBookings: 125,
    },
    {
      period: 'Mai',
      sales: 70,
      value: 175000,
      calls: 1050,
      followUpSales: 28,
      outboundBookings: 155,
    },
    {
      period: 'Iun',
      sales: 75,
      value: 187500,
      calls: 1150,
      followUpSales: 32,
      outboundBookings: 175,
    },
    {
      period: 'Iul',
      sales: 78,
      value: 195000,
      calls: 1180,
      followUpSales: 35,
      outboundBookings: 185,
    },
    {
      period: 'Aug',
      sales: 72,
      value: 180000,
      calls: 1100,
      followUpSales: 30,
      outboundBookings: 170,
    },
    {
      period: 'Sep',
      sales: 85,
      value: 212500,
      calls: 1300,
      followUpSales: 40,
      outboundBookings: 200,
    },
    {
      period: 'Oct',
      sales: 90,
      value: 225000,
      calls: 1400,
      followUpSales: 45,
      outboundBookings: 220,
    },
    {
      period: 'Nov',
      sales: 95,
      value: 237500,
      calls: 1450,
      followUpSales: 48,
      outboundBookings: 230,
    },
    {
      period: 'Dec',
      sales: 100,
      value: 250000,
      calls: 1500,
      followUpSales: 50,
      outboundBookings: 240,
    },
  ],
};

export const teamHistory = {
  all: {
    last7Days: [
      {
        period: '6 days ago',
        sales: 6,
        calls: 110,
        followUpSales: 3,
        outboundBookings: 14,
        value: 7200,
      },
      {
        period: '5 days ago',
        sales: 8,
        calls: 130,
        followUpSales: 4,
        outboundBookings: 18,
        value: 9200,
      },
      {
        period: '4 days ago',
        sales: 5,
        calls: 95,
        followUpSales: 2,
        outboundBookings: 12,
        value: 6400,
      },
      {
        period: '3 days ago',
        sales: 10,
        calls: 150,
        followUpSales: 6,
        outboundBookings: 22,
        value: 11800,
      },
      {
        period: '2 days ago',
        sales: 9,
        calls: 140,
        followUpSales: 5,
        outboundBookings: 20,
        value: 10400,
      },
      {
        period: 'Yesterday',
        sales: 12,
        calls: 170,
        followUpSales: 7,
        outboundBookings: 26,
        value: 14200,
      },
      {
        period: 'Today',
        sales: 7,
        calls: 125,
        followUpSales: 4,
        outboundBookings: 16,
        value: 8600,
      },
    ],
    currentMonth: [
      {
        period: 'Sapt. 1',
        sales: 32,
        value: 78000,
        calls: 520,
        followUpSales: 12,
        outboundBookings: 64,
      },
      {
        period: 'Sapt. 2',
        sales: 38,
        value: 92000,
        calls: 600,
        followUpSales: 16,
        outboundBookings: 72,
      },
      {
        period: 'Sapt. 3',
        sales: 30,
        value: 70000,
        calls: 560,
        followUpSales: 11,
        outboundBookings: 58,
      },
      {
        period: 'Sapt. 4',
        sales: 42,
        value: 101000,
        calls: 640,
        followUpSales: 19,
        outboundBookings: 80,
      },
    ],
    currentYear: [
      {
        period: 'Ian',
        sales: 120,
        value: 280000,
        calls: 1900,
        followUpSales: 38,
        outboundBookings: 230,
      },
      {
        period: 'Feb',
        sales: 110,
        value: 260000,
        calls: 1750,
        followUpSales: 35,
        outboundBookings: 210,
      },
      {
        period: 'Mar',
        sales: 140,
        value: 320000,
        calls: 2100,
        followUpSales: 48,
        outboundBookings: 260,
      },
      {
        period: 'Apr',
        sales: 135,
        value: 305000,
        calls: 2000,
        followUpSales: 44,
        outboundBookings: 245,
      },
      {
        period: 'Mai',
        sales: 150,
        value: 340000,
        calls: 2250,
        followUpSales: 52,
        outboundBookings: 280,
      },
      {
        period: 'Iun',
        sales: 160,
        value: 360000,
        calls: 2400,
        followUpSales: 58,
        outboundBookings: 300,
      },
      {
        period: 'Iul',
        sales: 155,
        value: 350000,
        calls: 2350,
        followUpSales: 56,
        outboundBookings: 290,
      },
      {
        period: 'Aug',
        sales: 0,
        value: 0,
        calls: 0,
        followUpSales: 0,
        outboundBookings: 0,
      },
      {
        period: 'Sep',
        sales: 0,
        value: 0,
        calls: 0,
        followUpSales: 0,
        outboundBookings: 0,
      },
      {
        period: 'Oct',
        sales: 0,
        value: 0,
        calls: 0,
        followUpSales: 0,
        outboundBookings: 0,
      },
      {
        period: 'Nov',
        sales: 0,
        value: 0,
        calls: 0,
        followUpSales: 0,
        outboundBookings: 0,
      },
      {
        period: 'Dec',
        sales: 0,
        value: 0,
        calls: 0,
        followUpSales: 0,
        outboundBookings: 0,
      },
    ],
    previousYear: [
      {
        period: 'Ian',
        sales: 100,
        value: 240000,
        calls: 1700,
        followUpSales: 32,
        outboundBookings: 200,
      },
      {
        period: 'Feb',
        sales: 95,
        value: 225000,
        calls: 1600,
        followUpSales: 30,
        outboundBookings: 190,
      },
      {
        period: 'Mar',
        sales: 125,
        value: 290000,
        calls: 1950,
        followUpSales: 40,
        outboundBookings: 235,
      },
      {
        period: 'Apr',
        sales: 118,
        value: 275000,
        calls: 1850,
        followUpSales: 38,
        outboundBookings: 225,
      },
      {
        period: 'Mai',
        sales: 130,
        value: 305000,
        calls: 2050,
        followUpSales: 44,
        outboundBookings: 250,
      },
      {
        period: 'Iun',
        sales: 140,
        value: 320000,
        calls: 2200,
        followUpSales: 48,
        outboundBookings: 270,
      },
      {
        period: 'Iul',
        sales: 145,
        value: 330000,
        calls: 2300,
        followUpSales: 50,
        outboundBookings: 280,
      },
      {
        period: 'Aug',
        sales: 132,
        value: 310000,
        calls: 2100,
        followUpSales: 46,
        outboundBookings: 260,
      },
      {
        period: 'Sep',
        sales: 150,
        value: 350000,
        calls: 2400,
        followUpSales: 54,
        outboundBookings: 300,
      },
      {
        period: 'Oct',
        sales: 155,
        value: 365000,
        calls: 2500,
        followUpSales: 58,
        outboundBookings: 315,
      },
      {
        period: 'Nov',
        sales: 160,
        value: 380000,
        calls: 2550,
        followUpSales: 60,
        outboundBookings: 320,
      },
      {
        period: 'Dec',
        sales: 170,
        value: 400000,
        calls: 2650,
        followUpSales: 64,
        outboundBookings: 330,
      },
    ],
  },
  'alex-d': personalHistory,
  'john-p': {
    last7Days: [
      {
        period: '6 days ago',
        sales: 1,
        calls: 25,
        followUpSales: 1,
        outboundBookings: 3,
        value: 1600,
      },
      {
        period: '5 days ago',
        sales: 2,
        calls: 35,
        followUpSales: 1,
        outboundBookings: 4,
        value: 2200,
      },
      {
        period: '4 days ago',
        sales: 1,
        calls: 30,
        followUpSales: 0,
        outboundBookings: 3,
        value: 1400,
      },
      {
        period: '3 days ago',
        sales: 3,
        calls: 42,
        followUpSales: 1,
        outboundBookings: 5,
        value: 3600,
      },
      {
        period: '2 days ago',
        sales: 2,
        calls: 38,
        followUpSales: 1,
        outboundBookings: 4,
        value: 2600,
      },
      {
        period: 'Yesterday',
        sales: 3,
        calls: 46,
        followUpSales: 2,
        outboundBookings: 6,
        value: 3900,
      },
      {
        period: 'Today',
        sales: 2,
        calls: 34,
        followUpSales: 1,
        outboundBookings: 4,
        value: 2500,
      },
    ],
    currentMonth: [
      {
        period: 'Sapt. 1',
        sales: 10,
        value: 24000,
        calls: 180,
        followUpSales: 3,
        outboundBookings: 18,
      },
      {
        period: 'Sapt. 2',
        sales: 12,
        value: 28000,
        calls: 200,
        followUpSales: 4,
        outboundBookings: 20,
      },
      {
        period: 'Sapt. 3',
        sales: 9,
        value: 21000,
        calls: 190,
        followUpSales: 3,
        outboundBookings: 17,
      },
      {
        period: 'Sapt. 4',
        sales: 14,
        value: 32000,
        calls: 220,
        followUpSales: 5,
        outboundBookings: 22,
      },
    ],
    currentYear: [
      {
        period: 'Ian',
        sales: 35,
        value: 82000,
        calls: 520,
        followUpSales: 10,
        outboundBookings: 60,
      },
      {
        period: 'Feb',
        sales: 32,
        value: 76000,
        calls: 490,
        followUpSales: 9,
        outboundBookings: 55,
      },
      {
        period: 'Mar',
        sales: 40,
        value: 94000,
        calls: 560,
        followUpSales: 12,
        outboundBookings: 66,
      },
      {
        period: 'Apr',
        sales: 38,
        value: 89000,
        calls: 540,
        followUpSales: 11,
        outboundBookings: 63,
      },
      {
        period: 'Mai',
        sales: 42,
        value: 99000,
        calls: 580,
        followUpSales: 13,
        outboundBookings: 70,
      },
      {
        period: 'Iun',
        sales: 44,
        value: 103000,
        calls: 610,
        followUpSales: 14,
        outboundBookings: 72,
      },
      {
        period: 'Iul',
        sales: 45,
        value: 105000,
        calls: 620,
        followUpSales: 15,
        outboundBookings: 75,
      },
      {
        period: 'Aug',
        sales: 0,
        value: 0,
        calls: 0,
        followUpSales: 0,
        outboundBookings: 0,
      },
      {
        period: 'Sep',
        sales: 0,
        value: 0,
        calls: 0,
        followUpSales: 0,
        outboundBookings: 0,
      },
      {
        period: 'Oct',
        sales: 0,
        value: 0,
        calls: 0,
        followUpSales: 0,
        outboundBookings: 0,
      },
      {
        period: 'Nov',
        sales: 0,
        value: 0,
        calls: 0,
        followUpSales: 0,
        outboundBookings: 0,
      },
      {
        period: 'Dec',
        sales: 0,
        value: 0,
        calls: 0,
        followUpSales: 0,
        outboundBookings: 0,
      },
    ],
    previousYear: [
      {
        period: 'Ian',
        sales: 28,
        value: 68000,
        calls: 460,
        followUpSales: 8,
        outboundBookings: 52,
      },
      {
        period: 'Feb',
        sales: 26,
        value: 64000,
        calls: 440,
        followUpSales: 7,
        outboundBookings: 48,
      },
      {
        period: 'Mar',
        sales: 34,
        value: 80000,
        calls: 500,
        followUpSales: 10,
        outboundBookings: 58,
      },
      {
        period: 'Apr',
        sales: 32,
        value: 76000,
        calls: 480,
        followUpSales: 9,
        outboundBookings: 55,
      },
      {
        period: 'Mai',
        sales: 36,
        value: 85000,
        calls: 520,
        followUpSales: 11,
        outboundBookings: 62,
      },
      {
        period: 'Iun',
        sales: 38,
        value: 90000,
        calls: 540,
        followUpSales: 12,
        outboundBookings: 65,
      },
      {
        period: 'Iul',
        sales: 40,
        value: 94000,
        calls: 560,
        followUpSales: 13,
        outboundBookings: 68,
      },
      {
        period: 'Aug',
        sales: 36,
        value: 86000,
        calls: 520,
        followUpSales: 11,
        outboundBookings: 62,
      },
      {
        period: 'Sep',
        sales: 42,
        value: 100000,
        calls: 590,
        followUpSales: 14,
        outboundBookings: 74,
      },
      {
        period: 'Oct',
        sales: 45,
        value: 106000,
        calls: 620,
        followUpSales: 16,
        outboundBookings: 78,
      },
      {
        period: 'Nov',
        sales: 48,
        value: 112000,
        calls: 640,
        followUpSales: 17,
        outboundBookings: 80,
      },
      {
        period: 'Dec',
        sales: 52,
        value: 120000,
        calls: 680,
        followUpSales: 18,
        outboundBookings: 84,
      },
    ],
  },
  'maria-i': {
    last7Days: [
      {
        period: '6 days ago',
        sales: 2,
        calls: 28,
        followUpSales: 1,
        outboundBookings: 4,
        value: 1800,
      },
      {
        period: '5 days ago',
        sales: 3,
        calls: 32,
        followUpSales: 1,
        outboundBookings: 5,
        value: 2500,
      },
      {
        period: '4 days ago',
        sales: 2,
        calls: 26,
        followUpSales: 1,
        outboundBookings: 4,
        value: 2100,
      },
      {
        period: '3 days ago',
        sales: 4,
        calls: 40,
        followUpSales: 2,
        outboundBookings: 6,
        value: 3600,
      },
      {
        period: '2 days ago',
        sales: 4,
        calls: 38,
        followUpSales: 2,
        outboundBookings: 6,
        value: 3400,
      },
      {
        period: 'Yesterday',
        sales: 6,
        calls: 50,
        followUpSales: 3,
        outboundBookings: 8,
        value: 5200,
      },
      {
        period: 'Today',
        sales: 3,
        calls: 36,
        followUpSales: 1,
        outboundBookings: 5,
        value: 2700,
      },
    ],
    currentMonth: [
      {
        period: 'Sapt. 1',
        sales: 8,
        value: 19000,
        calls: 160,
        followUpSales: 3,
        outboundBookings: 18,
      },
      {
        period: 'Sapt. 2',
        sales: 10,
        value: 22000,
        calls: 180,
        followUpSales: 4,
        outboundBookings: 20,
      },
      {
        period: 'Sapt. 3',
        sales: 9,
        value: 20000,
        calls: 170,
        followUpSales: 3,
        outboundBookings: 19,
      },
      {
        period: 'Sapt. 4',
        sales: 12,
        value: 26000,
        calls: 200,
        followUpSales: 5,
        outboundBookings: 22,
      },
    ],
    currentYear: [
      {
        period: 'Ian',
        sales: 30,
        value: 69000,
        calls: 510,
        followUpSales: 10,
        outboundBookings: 60,
      },
      {
        period: 'Feb',
        sales: 28,
        value: 64000,
        calls: 480,
        followUpSales: 9,
        outboundBookings: 56,
      },
      {
        period: 'Mar',
        sales: 34,
        value: 78000,
        calls: 540,
        followUpSales: 11,
        outboundBookings: 66,
      },
      {
        period: 'Apr',
        sales: 32,
        value: 73000,
        calls: 520,
        followUpSales: 10,
        outboundBookings: 62,
      },
      {
        period: 'Mai',
        sales: 36,
        value: 83000,
        calls: 570,
        followUpSales: 12,
        outboundBookings: 70,
      },
      {
        period: 'Iun',
        sales: 38,
        value: 87000,
        calls: 590,
        followUpSales: 13,
        outboundBookings: 72,
      },
      {
        period: 'Iul',
        sales: 40,
        value: 91000,
        calls: 620,
        followUpSales: 14,
        outboundBookings: 76,
      },
      {
        period: 'Aug',
        sales: 0,
        value: 0,
        calls: 0,
        followUpSales: 0,
        outboundBookings: 0,
      },
      {
        period: 'Sep',
        sales: 0,
        value: 0,
        calls: 0,
        followUpSales: 0,
        outboundBookings: 0,
      },
      {
        period: 'Oct',
        sales: 0,
        value: 0,
        calls: 0,
        followUpSales: 0,
        outboundBookings: 0,
      },
      {
        period: 'Nov',
        sales: 0,
        value: 0,
        calls: 0,
        followUpSales: 0,
        outboundBookings: 0,
      },
      {
        period: 'Dec',
        sales: 0,
        value: 0,
        calls: 0,
        followUpSales: 0,
        outboundBookings: 0,
      },
    ],
    previousYear: [
      {
        period: 'Ian',
        sales: 25,
        value: 60000,
        calls: 450,
        followUpSales: 8,
        outboundBookings: 50,
      },
      {
        period: 'Feb',
        sales: 22,
        value: 54000,
        calls: 420,
        followUpSales: 7,
        outboundBookings: 46,
      },
      {
        period: 'Mar',
        sales: 30,
        value: 70000,
        calls: 500,
        followUpSales: 10,
        outboundBookings: 58,
      },
      {
        period: 'Apr',
        sales: 28,
        value: 66000,
        calls: 480,
        followUpSales: 9,
        outboundBookings: 54,
      },
      {
        period: 'Mai',
        sales: 32,
        value: 76000,
        calls: 520,
        followUpSales: 11,
        outboundBookings: 62,
      },
      {
        period: 'Iun',
        sales: 34,
        value: 80000,
        calls: 540,
        followUpSales: 12,
        outboundBookings: 66,
      },
      {
        period: 'Iul',
        sales: 36,
        value: 84000,
        calls: 560,
        followUpSales: 13,
        outboundBookings: 68,
      },
      {
        period: 'Aug',
        sales: 33,
        value: 78000,
        calls: 520,
        followUpSales: 11,
        outboundBookings: 64,
      },
      {
        period: 'Sep',
        sales: 38,
        value: 90000,
        calls: 590,
        followUpSales: 14,
        outboundBookings: 74,
      },
      {
        period: 'Oct',
        sales: 40,
        value: 95000,
        calls: 620,
        followUpSales: 15,
        outboundBookings: 78,
      },
      {
        period: 'Nov',
        sales: 42,
        value: 100000,
        calls: 640,
        followUpSales: 16,
        outboundBookings: 80,
      },
      {
        period: 'Dec',
        sales: 45,
        value: 108000,
        calls: 680,
        followUpSales: 18,
        outboundBookings: 84,
      },
    ],
  },
};
