import { CheckCircle2, Edit, XCircle } from 'lucide-react';

export const agents = [
  { id: 'alex-d', name: 'Alex Doe' },
  { id: 'john-p', name: 'John Popescu' },
  { id: 'maria-i', name: 'Maria Ionescu' },
];

export const teamPerformanceData = {
  calls: {
    '7': [
      { day: 'Luni', 'Alex Doe': 32, 'John Popescu': 25, 'Maria Ionescu': 40 },
      { day: 'Marți', 'Alex Doe': 45, 'John Popescu': 38, 'Maria Ionescu': 50 },
      {
        day: 'Miercuri',
        'Alex Doe': 28,
        'John Popescu': 33,
        'Maria Ionescu': 35,
      },
      { day: 'Joi', 'Alex Doe': 52, 'John Popescu': 48, 'Maria Ionescu': 55 },
      {
        day: 'Vineri',
        'Alex Doe': 61,
        'John Popescu': 55,
        'Maria Ionescu': 65,
      },
    ],
    '30': [
      {
        day: 'Săpt. 1',
        'Alex Doe': 218,
        'John Popescu': 190,
        'Maria Ionescu': 240,
      },
      {
        day: 'Săpt. 2',
        'Alex Doe': 250,
        'John Popescu': 220,
        'Maria Ionescu': 260,
      },
      {
        day: 'Săpt. 3',
        'Alex Doe': 230,
        'John Popescu': 210,
        'Maria Ionescu': 250,
      },
      {
        day: 'Săpt. 4',
        'Alex Doe': 280,
        'John Popescu': 260,
        'Maria Ionescu': 300,
      },
    ],
  },
  sales: {
    '7': [
      { day: 'Luni', 'Alex Doe': 2, 'John Popescu': 1, 'Maria Ionescu': 3 },
      { day: 'Marți', 'Alex Doe': 3, 'John Popescu': 2, 'Maria Ionescu': 4 },
      {
        day: 'Miercuri',
        'Alex Doe': 1,
        'John Popescu': 2,
        'Maria Ionescu': 2,
      },
      { day: 'Joi', 'Alex Doe': 4, 'John Popescu': 3, 'Maria Ionescu': 5 },
      { day: 'Vineri', 'Alex Doe': 5, 'John Popescu': 4, 'Maria Ionescu': 6 },
    ],
    '30': [
      {
        day: 'Săpt. 1',
        'Alex Doe': 15,
        'John Popescu': 12,
        'Maria Ionescu': 18,
      },
      {
        day: 'Săpt. 2',
        'Alex Doe': 18,
        'John Popescu': 15,
        'Maria Ionescu': 20,
      },
      {
        day: 'Săpt. 3',
        'Alex Doe': 16,
        'John Popescu': 14,
        'Maria Ionescu': 19,
      },
      {
        day: 'Săpt. 4',
        'Alex Doe': 22,
        'John Popescu': 19,
        'Maria Ionescu': 25,
      },
    ],
  },
};

export const agentReports = {
  'alex-d': {
    status: 'submitted',
    data: {
      outbound_dials: 61,
      pickups: 40,
      conversations_30s_plus: 35,
      sales_call_booked_from_outbound: 8,
      sales_call_on_calendar: 7,
      no_show: 1,
      reschedule_request: 0,
      cancel: 0,
      deposits: 5,
      sales_one_call_close: 3,
      followup_sales: 2,
      upsell_conversation_taken: 4,
      upsells: 1,
      contract_value: 12500,
      new_cash_collected: 5000,
      observations:
        'O zi productivă, majoritatea clienților au fost receptivi.',
      confirmation: true,
    },
  },
  'john-p': {
    status: 'draft',
    data: {
      outbound_dials: 55,
      pickups: 35,
      conversations_30s_plus: 30,
      sales_call_booked_from_outbound: 6,
      sales_call_on_calendar: 6,
      no_show: 0,
      reschedule_request: 1,
      cancel: 0,
      deposits: 4,
      sales_one_call_close: 2,
      followup_sales: 2,
      upsell_conversation_taken: 3,
      upsells: 1,
      contract_value: 9800,
      new_cash_collected: 4200,
      observations: 'Am avut câteva reprogramări. Follow-up necesar mâine.',
      confirmation: false,
    },
  },
  'maria-i': {
    status: 'unfilled',
    data: {
      outbound_dials: 0,
      pickups: 0,
      conversations_30s_plus: 0,
      sales_call_booked_from_outbound: 0,
      sales_call_on_calendar: 0,
      no_show: 0,
      reschedule_request: 0,
      cancel: 0,
      deposits: 0,
      sales_one_call_close: 0,
      followup_sales: 0,
      upsell_conversation_taken: 0,
      upsells: 0,
      contract_value: 0,
      new_cash_collected: 0,
      observations: '',
      confirmation: false,
    },
  },
};

export const managerNotifications = [
  {
    id: 1,
    agent: 'Alex Doe',
    agentAvatarId: 'avatar-2',
    text: 'a trimis raportul zilnic.',
    time: 'Acum 5 minute',
    read: false,
  },
  {
    id: 2,
    agent: 'John Popescu',
    agentAvatarId: 'avatar-1',
    text: 'a salvat un draft pentru raportul zilnic.',
    time: 'Acum 30 minute',
    read: false,
  },
  {
    id: 3,
    agent: 'Alex Doe',
    agentAvatarId: 'avatar-2',
    text: 'a închis o vânzare de 2,500 RON.',
    time: 'Acum 2 ore',
    read: true,
  },
  {
    id: 4,
    agent: 'Maria Ionescu',
    agentAvatarId: 'avatar-3',
    text: 'a solicitat editarea raportului de ieri.',
    time: 'Ieri',
    read: true,
  },
];

export const reportStatusConfig = {
  submitted: { text: 'Trimis', Icon: CheckCircle2, color: 'text-green-500' },
  draft: { text: 'Draft', Icon: Edit, color: 'text-yellow-500' },
  unfilled: { text: 'Necompletat', Icon: XCircle, color: 'text-destructive' },
  locked: { text: 'Blocat', Icon: XCircle, color: 'text-muted-foreground' },
};

export const quickStats = {
  all: {
    calls: 116,
    conversions: 14,
    sales: 7,
    value: '$22,300',
  },
  'alex-d': {
    calls: 61,
    conversions: 8,
    sales: 5,
    value: '$12,500',
  },
  'john-p': {
    calls: 55,
    conversions: 6,
    sales: 4,
    value: '$9,800',
  },
  'maria-i': {
    calls: 0,
    conversions: 0,
    sales: 0,
    value: '$0',
  },
};

export const personalHistory = {
  last7Days: [
    {
      period: 'Acum 6 zile',
      sales: 2,
      calls: 30,
      followUpSales: 1,
      outboundBookings: 5,
    },
    {
      period: 'Acum 5 zile',
      sales: 3,
      calls: 45,
      followUpSales: 1,
      outboundBookings: 7,
    },
    {
      period: 'Acum 4 zile',
      sales: 1,
      calls: 28,
      followUpSales: 0,
      outboundBookings: 4,
    },
    {
      period: 'Acum 3 zile',
      sales: 4,
      calls: 52,
      followUpSales: 2,
      outboundBookings: 8,
    },
    {
      period: 'Acum 2 zile',
      sales: 3,
      calls: 48,
      followUpSales: 1,
      outboundBookings: 6,
    },
    {
      period: 'Ieri',
      sales: 5,
      calls: 61,
      followUpSales: 3,
      outboundBookings: 10,
    },
    {
      period: 'Azi',
      sales: 2,
      calls: 35,
      followUpSales: 1,
      outboundBookings: 4,
    },
  ],
  currentMonth: [
    {
      period: 'Săpt. 1',
      sales: 15,
      value: 37500,
      calls: 218,
      followUpSales: 5,
      outboundBookings: 30,
    },
    {
      period: 'Săpt. 2',
      sales: 18,
      value: 45000,
      calls: 250,
      followUpSales: 7,
      outboundBookings: 35,
    },
    {
      period: 'Săpt. 3',
      sales: 12,
      value: 30000,
      calls: 230,
      followUpSales: 4,
      outboundBookings: 28,
    },
    {
      period: 'Săpt. 4',
      sales: 20,
      value: 50000,
      calls: 280,
      followUpSales: 9,
      outboundBookings: 40,
    },
  ],
  currentYear: [
    {
      period: 'Ian',
      sales: 60,
      value: 150000,
      calls: 900,
      followUpSales: 20,
      outboundBookings: 120,
    },
    {
      period: 'Feb',
      sales: 55,
      value: 137500,
      calls: 850,
      followUpSales: 18,
      outboundBookings: 110,
    },
    {
      period: 'Mar',
      sales: 70,
      value: 175000,
      calls: 1000,
      followUpSales: 25,
      outboundBookings: 150,
    },
    {
      period: 'Apr',
      sales: 65,
      value: 162500,
      calls: 950,
      followUpSales: 22,
      outboundBookings: 140,
    },
    {
      period: 'Mai',
      sales: 75,
      value: 187500,
      calls: 1100,
      followUpSales: 30,
      outboundBookings: 160,
    },
    {
      period: 'Iun',
      sales: 80,
      value: 200000,
      calls: 1200,
      followUpSales: 35,
      outboundBookings: 180,
    },
    {
      period: 'Iul',
      sales: 82,
      value: 205000,
      calls: 1250,
      followUpSales: 38,
      outboundBookings: 190,
    },
    {
      period: 'Aug',
      sales: 0,
      value: 0,
      calls: 0,
      followUpSales: 0,
      outboundBookings: 0,
    },
    {
      period: 'Sep',
      sales: 0,
      value: 0,
      calls: 0,
      followUpSales: 0,
      outboundBookings: 0,
    },
    {
      period: 'Oct',
      sales: 0,
      value: 0,
      calls: 0,
      followUpSales: 0,
      outboundBookings: 0,
    },
    {
      period: 'Nov',
      sales: 0,
      value: 0,
      calls: 0,
      followUpSales: 0,
      outboundBookings: 0,
    },
    {
      period: 'Dec',
      sales: 0,
      value: 0,
      calls: 0,
      followUpSales: 0,
      outboundBookings: 0,
    },
  ],
  previousYear: [
    {
      period: 'Ian',
      sales: 50,
      value: 125000,
      calls: 800,
      followUpSales: 15,
      outboundBookings: 100,
    },
    {
      period: 'Feb',
      sales: 48,
      value: 120000,
      calls: 780,
      followUpSales: 14,
      outboundBookings: 95,
    },
    {
      period: 'Mar',
      sales: 65,
      value: 162500,
      calls: 950,
      followUpSales: 20,
      outboundBookings: 130,
    },
    {
      period: 'Apr',
      sales: 62,
      value: 155000,
      calls: 920,
      followUpSales: 19,
      outboundBookings: 125,
    },
    {
      period: 'Mai',
      sales: 70,
      value: 175000,
      calls: 1050,
      followUpSales: 28,
      outboundBookings: 155,
    },
    {
      period: 'Iun',
      sales: 75,
      value: 187500,
      calls: 1150,
      followUpSales: 32,
      outboundBookings: 175,
    },
    {
      period: 'Iul',
      sales: 78,
      value: 195000,
      calls: 1180,
      followUpSales: 35,
      outboundBookings: 185,
    },
    {
      period: 'Aug',
      sales: 72,
      value: 180000,
      calls: 1100,
      followUpSales: 30,
      outboundBookings: 170,
    },
    {
      period: 'Sep',
      sales: 85,
      value: 212500,
      calls: 1300,
      followUpSales: 40,
      outboundBookings: 200,
    },
    {
      period: 'Oct',
      sales: 90,
      value: 225000,
      calls: 1400,
      followUpSales: 45,
      outboundBookings: 220,
    },
    {
      period: 'Nov',
      sales: 95,
      value: 237500,
      calls: 1450,
      followUpSales: 48,
      outboundBookings: 230,
    },
    {
      period: 'Dec',
      sales: 100,
      value: 250000,
      calls: 1500,
      followUpSales: 50,
      outboundBookings: 240,
    },
  ],
};
